/**
 * This class is generated by jOOQ
 */
package com.example.mysql.tables.records;


import com.example.mysql.tables.Plugin;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * MySQL plugins
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PluginRecord extends UpdatableRecordImpl<PluginRecord> implements Record2<String, String> {

	private static final long serialVersionUID = -109376048;

	/**
	 * Setter for <code>mysql.plugin.name</code>.
	 */
	public void setName(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mysql.plugin.name</code>.
	 */
	public String getName() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>mysql.plugin.dl</code>.
	 */
	public void setDl(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mysql.plugin.dl</code>.
	 */
	public String getDl() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Plugin.PLUGIN.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Plugin.PLUGIN.DL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getDl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PluginRecord value1(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PluginRecord value2(String value) {
		setDl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PluginRecord values(String value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PluginRecord
	 */
	public PluginRecord() {
		super(Plugin.PLUGIN);
	}

	/**
	 * Create a detached, initialised PluginRecord
	 */
	public PluginRecord(String name, String dl) {
		super(Plugin.PLUGIN);

		setValue(0, name);
		setValue(1, dl);
	}
}
