/**
 * This class is generated by jOOQ
 */
package com.example.mysql.tables.records;


import com.example.mysql.tables.TimeZoneName;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * Time zone names
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TimeZoneNameRecord extends UpdatableRecordImpl<TimeZoneNameRecord> implements Record2<String, UInteger> {

	private static final long serialVersionUID = 945909922;

	/**
	 * Setter for <code>mysql.time_zone_name.Name</code>.
	 */
	public void setName(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mysql.time_zone_name.Name</code>.
	 */
	public String getName() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>mysql.time_zone_name.Time_zone_id</code>.
	 */
	public void setTimeZoneId(UInteger value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mysql.time_zone_name.Time_zone_id</code>.
	 */
	public UInteger getTimeZoneId() {
		return (UInteger) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, UInteger> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, UInteger> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return TimeZoneName.TIME_ZONE_NAME.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UInteger> field2() {
		return TimeZoneName.TIME_ZONE_NAME.TIME_ZONE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UInteger value2() {
		return getTimeZoneId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeZoneNameRecord value1(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeZoneNameRecord value2(UInteger value) {
		setTimeZoneId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeZoneNameRecord values(String value1, UInteger value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TimeZoneNameRecord
	 */
	public TimeZoneNameRecord() {
		super(TimeZoneName.TIME_ZONE_NAME);
	}

	/**
	 * Create a detached, initialised TimeZoneNameRecord
	 */
	public TimeZoneNameRecord(String name, UInteger timeZoneId) {
		super(TimeZoneName.TIME_ZONE_NAME);

		setValue(0, name);
		setValue(1, timeZoneId);
	}
}
