/**
 * This class is generated by jOOQ
 */
package com.example.performance_schema.tables;


import com.example.performance_schema.PerformanceSchema;
import com.example.performance_schema.tables.records.MutexInstancesRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MutexInstances extends TableImpl<MutexInstancesRecord> {

	private static final long serialVersionUID = 1396355282;

	/**
	 * The reference instance of <code>performance_schema.mutex_instances</code>
	 */
	public static final MutexInstances MUTEX_INSTANCES = new MutexInstances();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<MutexInstancesRecord> getRecordType() {
		return MutexInstancesRecord.class;
	}

	/**
	 * The column <code>performance_schema.mutex_instances.NAME</code>.
	 */
	public final TableField<MutexInstancesRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

	/**
	 * The column <code>performance_schema.mutex_instances.OBJECT_INSTANCE_BEGIN</code>.
	 */
	public final TableField<MutexInstancesRecord, ULong> OBJECT_INSTANCE_BEGIN = createField("OBJECT_INSTANCE_BEGIN", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>performance_schema.mutex_instances.LOCKED_BY_THREAD_ID</code>.
	 */
	public final TableField<MutexInstancesRecord, ULong> LOCKED_BY_THREAD_ID = createField("LOCKED_BY_THREAD_ID", org.jooq.impl.SQLDataType.BIGINTUNSIGNED, this, "");

	/**
	 * Create a <code>performance_schema.mutex_instances</code> table reference
	 */
	public MutexInstances() {
		this("mutex_instances", null);
	}

	/**
	 * Create an aliased <code>performance_schema.mutex_instances</code> table reference
	 */
	public MutexInstances(String alias) {
		this(alias, MUTEX_INSTANCES);
	}

	private MutexInstances(String alias, Table<MutexInstancesRecord> aliased) {
		this(alias, aliased, null);
	}

	private MutexInstances(String alias, Table<MutexInstancesRecord> aliased, Field<?>[] parameters) {
		super(alias, PerformanceSchema.PERFORMANCE_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MutexInstances as(String alias) {
		return new MutexInstances(alias, this);
	}

	/**
	 * Rename this table
	 */
	public MutexInstances rename(String name) {
		return new MutexInstances(name, null);
	}
}
