/**
 * This class is generated by jOOQ
 */
package com.example.performance_schema.tables;


import com.example.performance_schema.PerformanceSchema;
import com.example.performance_schema.enums.SetupObjectsEnabled;
import com.example.performance_schema.enums.SetupObjectsObjectType;
import com.example.performance_schema.enums.SetupObjectsTimed;
import com.example.performance_schema.tables.records.SetupObjectsRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SetupObjects extends TableImpl<SetupObjectsRecord> {

	private static final long serialVersionUID = 1005281396;

	/**
	 * The reference instance of <code>performance_schema.setup_objects</code>
	 */
	public static final SetupObjects SETUP_OBJECTS = new SetupObjects();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SetupObjectsRecord> getRecordType() {
		return SetupObjectsRecord.class;
	}

	/**
	 * The column <code>performance_schema.setup_objects.OBJECT_TYPE</code>.
	 */
	public final TableField<SetupObjectsRecord, SetupObjectsObjectType> OBJECT_TYPE = createField("OBJECT_TYPE", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.example.performance_schema.enums.SetupObjectsObjectType.class), this, "");

	/**
	 * The column <code>performance_schema.setup_objects.OBJECT_SCHEMA</code>.
	 */
	public final TableField<SetupObjectsRecord, String> OBJECT_SCHEMA = createField("OBJECT_SCHEMA", org.jooq.impl.SQLDataType.VARCHAR.length(64).defaulted(true), this, "");

	/**
	 * The column <code>performance_schema.setup_objects.OBJECT_NAME</code>.
	 */
	public final TableField<SetupObjectsRecord, String> OBJECT_NAME = createField("OBJECT_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>performance_schema.setup_objects.ENABLED</code>.
	 */
	public final TableField<SetupObjectsRecord, SetupObjectsEnabled> ENABLED = createField("ENABLED", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.example.performance_schema.enums.SetupObjectsEnabled.class), this, "");

	/**
	 * The column <code>performance_schema.setup_objects.TIMED</code>.
	 */
	public final TableField<SetupObjectsRecord, SetupObjectsTimed> TIMED = createField("TIMED", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.example.performance_schema.enums.SetupObjectsTimed.class), this, "");

	/**
	 * Create a <code>performance_schema.setup_objects</code> table reference
	 */
	public SetupObjects() {
		this("setup_objects", null);
	}

	/**
	 * Create an aliased <code>performance_schema.setup_objects</code> table reference
	 */
	public SetupObjects(String alias) {
		this(alias, SETUP_OBJECTS);
	}

	private SetupObjects(String alias, Table<SetupObjectsRecord> aliased) {
		this(alias, aliased, null);
	}

	private SetupObjects(String alias, Table<SetupObjectsRecord> aliased, Field<?>[] parameters) {
		super(alias, PerformanceSchema.PERFORMANCE_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SetupObjects as(String alias) {
		return new SetupObjects(alias, this);
	}

	/**
	 * Rename this table
	 */
	public SetupObjects rename(String name) {
		return new SetupObjects(name, null);
	}
}
