/**
 * This class is generated by jOOQ
 */
package com.example.performance_schema.tables;


import com.example.performance_schema.PerformanceSchema;
import com.example.performance_schema.tables.records.VariablesByThreadRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VariablesByThread extends TableImpl<VariablesByThreadRecord> {

	private static final long serialVersionUID = 2033795777;

	/**
	 * The reference instance of <code>performance_schema.variables_by_thread</code>
	 */
	public static final VariablesByThread VARIABLES_BY_THREAD = new VariablesByThread();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<VariablesByThreadRecord> getRecordType() {
		return VariablesByThreadRecord.class;
	}

	/**
	 * The column <code>performance_schema.variables_by_thread.THREAD_ID</code>.
	 */
	public final TableField<VariablesByThreadRecord, ULong> THREAD_ID = createField("THREAD_ID", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>performance_schema.variables_by_thread.VARIABLE_NAME</code>.
	 */
	public final TableField<VariablesByThreadRecord, String> VARIABLE_NAME = createField("VARIABLE_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

	/**
	 * The column <code>performance_schema.variables_by_thread.VARIABLE_VALUE</code>.
	 */
	public final TableField<VariablesByThreadRecord, String> VARIABLE_VALUE = createField("VARIABLE_VALUE", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * Create a <code>performance_schema.variables_by_thread</code> table reference
	 */
	public VariablesByThread() {
		this("variables_by_thread", null);
	}

	/**
	 * Create an aliased <code>performance_schema.variables_by_thread</code> table reference
	 */
	public VariablesByThread(String alias) {
		this(alias, VARIABLES_BY_THREAD);
	}

	private VariablesByThread(String alias, Table<VariablesByThreadRecord> aliased) {
		this(alias, aliased, null);
	}

	private VariablesByThread(String alias, Table<VariablesByThreadRecord> aliased, Field<?>[] parameters) {
		super(alias, PerformanceSchema.PERFORMANCE_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VariablesByThread as(String alias) {
		return new VariablesByThread(alias, this);
	}

	/**
	 * Rename this table
	 */
	public VariablesByThread rename(String name) {
		return new VariablesByThread(name, null);
	}
}
