/**
 * This class is generated by jOOQ
 */
package com.example.performance_schema.tables.records;


import com.example.performance_schema.tables.FileSummaryByInstance;

import javax.annotation.Generated;

import org.jooq.impl.TableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileSummaryByInstanceRecord extends TableRecordImpl<FileSummaryByInstanceRecord> {

	private static final long serialVersionUID = -1345867549;

	/**
	 * Setter for <code>performance_schema.file_summary_by_instance.FILE_NAME</code>.
	 */
	public void setFileName(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>performance_schema.file_summary_by_instance.FILE_NAME</code>.
	 */
	public String getFileName() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>performance_schema.file_summary_by_instance.EVENT_NAME</code>.
	 */
	public void setEventName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>performance_schema.file_summary_by_instance.EVENT_NAME</code>.
	 */
	public String getEventName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>performance_schema.file_summary_by_instance.OBJECT_INSTANCE_BEGIN</code>.
	 */
	public void setObjectInstanceBegin(ULong value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>performance_schema.file_summary_by_instance.OBJECT_INSTANCE_BEGIN</code>.
	 */
	public ULong getObjectInstanceBegin() {
		return (ULong) getValue(2);
	}

	/**
	 * Setter for <code>performance_schema.file_summary_by_instance.COUNT_STAR</code>.
	 */
	public void setCountStar(ULong value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>performance_schema.file_summary_by_instance.COUNT_STAR</code>.
	 */
	public ULong getCountStar() {
		return (ULong) getValue(3);
	}

	/**
	 * Setter for <code>performance_schema.file_summary_by_instance.SUM_TIMER_WAIT</code>.
	 */
	public void setSumTimerWait(ULong value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>performance_schema.file_summary_by_instance.SUM_TIMER_WAIT</code>.
	 */
	public ULong getSumTimerWait() {
		return (ULong) getValue(4);
	}

	/**
	 * Setter for <code>performance_schema.file_summary_by_instance.MIN_TIMER_WAIT</code>.
	 */
	public void setMinTimerWait(ULong value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>performance_schema.file_summary_by_instance.MIN_TIMER_WAIT</code>.
	 */
	public ULong getMinTimerWait() {
		return (ULong) getValue(5);
	}

	/**
	 * Setter for <code>performance_schema.file_summary_by_instance.AVG_TIMER_WAIT</code>.
	 */
	public void setAvgTimerWait(ULong value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>performance_schema.file_summary_by_instance.AVG_TIMER_WAIT</code>.
	 */
	public ULong getAvgTimerWait() {
		return (ULong) getValue(6);
	}

	/**
	 * Setter for <code>performance_schema.file_summary_by_instance.MAX_TIMER_WAIT</code>.
	 */
	public void setMaxTimerWait(ULong value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>performance_schema.file_summary_by_instance.MAX_TIMER_WAIT</code>.
	 */
	public ULong getMaxTimerWait() {
		return (ULong) getValue(7);
	}

	/**
	 * Setter for <code>performance_schema.file_summary_by_instance.COUNT_READ</code>.
	 */
	public void setCountRead(ULong value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>performance_schema.file_summary_by_instance.COUNT_READ</code>.
	 */
	public ULong getCountRead() {
		return (ULong) getValue(8);
	}

	/**
	 * Setter for <code>performance_schema.file_summary_by_instance.SUM_TIMER_READ</code>.
	 */
	public void setSumTimerRead(ULong value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>performance_schema.file_summary_by_instance.SUM_TIMER_READ</code>.
	 */
	public ULong getSumTimerRead() {
		return (ULong) getValue(9);
	}

	/**
	 * Setter for <code>performance_schema.file_summary_by_instance.MIN_TIMER_READ</code>.
	 */
	public void setMinTimerRead(ULong value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>performance_schema.file_summary_by_instance.MIN_TIMER_READ</code>.
	 */
	public ULong getMinTimerRead() {
		return (ULong) getValue(10);
	}

	/**
	 * Setter for <code>performance_schema.file_summary_by_instance.AVG_TIMER_READ</code>.
	 */
	public void setAvgTimerRead(ULong value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>performance_schema.file_summary_by_instance.AVG_TIMER_READ</code>.
	 */
	public ULong getAvgTimerRead() {
		return (ULong) getValue(11);
	}

	/**
	 * Setter for <code>performance_schema.file_summary_by_instance.MAX_TIMER_READ</code>.
	 */
	public void setMaxTimerRead(ULong value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>performance_schema.file_summary_by_instance.MAX_TIMER_READ</code>.
	 */
	public ULong getMaxTimerRead() {
		return (ULong) getValue(12);
	}

	/**
	 * Setter for <code>performance_schema.file_summary_by_instance.SUM_NUMBER_OF_BYTES_READ</code>.
	 */
	public void setSumNumberOfBytesRead(Long value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>performance_schema.file_summary_by_instance.SUM_NUMBER_OF_BYTES_READ</code>.
	 */
	public Long getSumNumberOfBytesRead() {
		return (Long) getValue(13);
	}

	/**
	 * Setter for <code>performance_schema.file_summary_by_instance.COUNT_WRITE</code>.
	 */
	public void setCountWrite(ULong value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>performance_schema.file_summary_by_instance.COUNT_WRITE</code>.
	 */
	public ULong getCountWrite() {
		return (ULong) getValue(14);
	}

	/**
	 * Setter for <code>performance_schema.file_summary_by_instance.SUM_TIMER_WRITE</code>.
	 */
	public void setSumTimerWrite(ULong value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>performance_schema.file_summary_by_instance.SUM_TIMER_WRITE</code>.
	 */
	public ULong getSumTimerWrite() {
		return (ULong) getValue(15);
	}

	/**
	 * Setter for <code>performance_schema.file_summary_by_instance.MIN_TIMER_WRITE</code>.
	 */
	public void setMinTimerWrite(ULong value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>performance_schema.file_summary_by_instance.MIN_TIMER_WRITE</code>.
	 */
	public ULong getMinTimerWrite() {
		return (ULong) getValue(16);
	}

	/**
	 * Setter for <code>performance_schema.file_summary_by_instance.AVG_TIMER_WRITE</code>.
	 */
	public void setAvgTimerWrite(ULong value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>performance_schema.file_summary_by_instance.AVG_TIMER_WRITE</code>.
	 */
	public ULong getAvgTimerWrite() {
		return (ULong) getValue(17);
	}

	/**
	 * Setter for <code>performance_schema.file_summary_by_instance.MAX_TIMER_WRITE</code>.
	 */
	public void setMaxTimerWrite(ULong value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>performance_schema.file_summary_by_instance.MAX_TIMER_WRITE</code>.
	 */
	public ULong getMaxTimerWrite() {
		return (ULong) getValue(18);
	}

	/**
	 * Setter for <code>performance_schema.file_summary_by_instance.SUM_NUMBER_OF_BYTES_WRITE</code>.
	 */
	public void setSumNumberOfBytesWrite(Long value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>performance_schema.file_summary_by_instance.SUM_NUMBER_OF_BYTES_WRITE</code>.
	 */
	public Long getSumNumberOfBytesWrite() {
		return (Long) getValue(19);
	}

	/**
	 * Setter for <code>performance_schema.file_summary_by_instance.COUNT_MISC</code>.
	 */
	public void setCountMisc(ULong value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>performance_schema.file_summary_by_instance.COUNT_MISC</code>.
	 */
	public ULong getCountMisc() {
		return (ULong) getValue(20);
	}

	/**
	 * Setter for <code>performance_schema.file_summary_by_instance.SUM_TIMER_MISC</code>.
	 */
	public void setSumTimerMisc(ULong value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>performance_schema.file_summary_by_instance.SUM_TIMER_MISC</code>.
	 */
	public ULong getSumTimerMisc() {
		return (ULong) getValue(21);
	}

	/**
	 * Setter for <code>performance_schema.file_summary_by_instance.MIN_TIMER_MISC</code>.
	 */
	public void setMinTimerMisc(ULong value) {
		setValue(22, value);
	}

	/**
	 * Getter for <code>performance_schema.file_summary_by_instance.MIN_TIMER_MISC</code>.
	 */
	public ULong getMinTimerMisc() {
		return (ULong) getValue(22);
	}

	/**
	 * Setter for <code>performance_schema.file_summary_by_instance.AVG_TIMER_MISC</code>.
	 */
	public void setAvgTimerMisc(ULong value) {
		setValue(23, value);
	}

	/**
	 * Getter for <code>performance_schema.file_summary_by_instance.AVG_TIMER_MISC</code>.
	 */
	public ULong getAvgTimerMisc() {
		return (ULong) getValue(23);
	}

	/**
	 * Setter for <code>performance_schema.file_summary_by_instance.MAX_TIMER_MISC</code>.
	 */
	public void setMaxTimerMisc(ULong value) {
		setValue(24, value);
	}

	/**
	 * Getter for <code>performance_schema.file_summary_by_instance.MAX_TIMER_MISC</code>.
	 */
	public ULong getMaxTimerMisc() {
		return (ULong) getValue(24);
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FileSummaryByInstanceRecord
	 */
	public FileSummaryByInstanceRecord() {
		super(FileSummaryByInstance.FILE_SUMMARY_BY_INSTANCE);
	}

	/**
	 * Create a detached, initialised FileSummaryByInstanceRecord
	 */
	public FileSummaryByInstanceRecord(String fileName, String eventName, ULong objectInstanceBegin, ULong countStar, ULong sumTimerWait, ULong minTimerWait, ULong avgTimerWait, ULong maxTimerWait, ULong countRead, ULong sumTimerRead, ULong minTimerRead, ULong avgTimerRead, ULong maxTimerRead, Long sumNumberOfBytesRead, ULong countWrite, ULong sumTimerWrite, ULong minTimerWrite, ULong avgTimerWrite, ULong maxTimerWrite, Long sumNumberOfBytesWrite, ULong countMisc, ULong sumTimerMisc, ULong minTimerMisc, ULong avgTimerMisc, ULong maxTimerMisc) {
		super(FileSummaryByInstance.FILE_SUMMARY_BY_INSTANCE);

		setValue(0, fileName);
		setValue(1, eventName);
		setValue(2, objectInstanceBegin);
		setValue(3, countStar);
		setValue(4, sumTimerWait);
		setValue(5, minTimerWait);
		setValue(6, avgTimerWait);
		setValue(7, maxTimerWait);
		setValue(8, countRead);
		setValue(9, sumTimerRead);
		setValue(10, minTimerRead);
		setValue(11, avgTimerRead);
		setValue(12, maxTimerRead);
		setValue(13, sumNumberOfBytesRead);
		setValue(14, countWrite);
		setValue(15, sumTimerWrite);
		setValue(16, minTimerWrite);
		setValue(17, avgTimerWrite);
		setValue(18, maxTimerWrite);
		setValue(19, sumNumberOfBytesWrite);
		setValue(20, countMisc);
		setValue(21, sumTimerMisc);
		setValue(22, minTimerMisc);
		setValue(23, avgTimerMisc);
		setValue(24, maxTimerMisc);
	}
}
