/**
 * This class is generated by jOOQ
 */
package com.example.performance_schema.enums;


import javax.annotation.Generated;

import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum PreparedStatementsInstancesOwnerObjectType implements EnumType {

	EVENT("EVENT"),

	FUNCTION("FUNCTION"),

	PROCEDURE("PROCEDURE"),

	TABLE("TABLE"),

	TRIGGER("TRIGGER");

	private final String literal;

	private PreparedStatementsInstancesOwnerObjectType(String literal) {
		this.literal = literal;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Schema getSchema() {
		return null;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String getName() {
		return "prepared_statements_instances_OWNER_OBJECT_TYPE";
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String getLiteral() {
		return literal;
	}
}
