/**
 * This class is generated by jOOQ
 */
package com.example.sys.tables.records;


import com.example.sys.tables.SchemaUnusedIndexes;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SchemaUnusedIndexesRecord extends TableRecordImpl<SchemaUnusedIndexesRecord> implements Record3<String, String, String> {

	private static final long serialVersionUID = -565909392;

	/**
	 * Setter for <code>sys.schema_unused_indexes.object_schema</code>.
	 */
	public void setObjectSchema(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sys.schema_unused_indexes.object_schema</code>.
	 */
	public String getObjectSchema() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>sys.schema_unused_indexes.object_name</code>.
	 */
	public void setObjectName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sys.schema_unused_indexes.object_name</code>.
	 */
	public String getObjectName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>sys.schema_unused_indexes.index_name</code>.
	 */
	public void setIndexName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sys.schema_unused_indexes.index_name</code>.
	 */
	public String getIndexName() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, String, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, String, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return SchemaUnusedIndexes.SCHEMA_UNUSED_INDEXES.OBJECT_SCHEMA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return SchemaUnusedIndexes.SCHEMA_UNUSED_INDEXES.OBJECT_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return SchemaUnusedIndexes.SCHEMA_UNUSED_INDEXES.INDEX_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getObjectSchema();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getObjectName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getIndexName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchemaUnusedIndexesRecord value1(String value) {
		setObjectSchema(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchemaUnusedIndexesRecord value2(String value) {
		setObjectName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchemaUnusedIndexesRecord value3(String value) {
		setIndexName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchemaUnusedIndexesRecord values(String value1, String value2, String value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SchemaUnusedIndexesRecord
	 */
	public SchemaUnusedIndexesRecord() {
		super(SchemaUnusedIndexes.SCHEMA_UNUSED_INDEXES);
	}

	/**
	 * Create a detached, initialised SchemaUnusedIndexesRecord
	 */
	public SchemaUnusedIndexesRecord(String objectSchema, String objectName, String indexName) {
		super(SchemaUnusedIndexes.SCHEMA_UNUSED_INDEXES);

		setValue(0, objectSchema);
		setValue(1, objectName);
		setValue(2, indexName);
	}
}
