/**
 * This class is generated by jOOQ
 */
package com.example.information_schema.tables;


import com.example.information_schema.InformationSchema;
import com.example.information_schema.tables.records.InnodbFtDefaultStopwordRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InnodbFtDefaultStopword extends TableImpl<InnodbFtDefaultStopwordRecord> {

	private static final long serialVersionUID = 1190042591;

	/**
	 * The reference instance of <code>information_schema.INNODB_FT_DEFAULT_STOPWORD</code>
	 */
	public static final InnodbFtDefaultStopword INNODB_FT_DEFAULT_STOPWORD = new InnodbFtDefaultStopword();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<InnodbFtDefaultStopwordRecord> getRecordType() {
		return InnodbFtDefaultStopwordRecord.class;
	}

	/**
	 * The column <code>information_schema.INNODB_FT_DEFAULT_STOPWORD.value</code>.
	 */
	public final TableField<InnodbFtDefaultStopwordRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR.length(18).nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>information_schema.INNODB_FT_DEFAULT_STOPWORD</code> table reference
	 */
	public InnodbFtDefaultStopword() {
		this("INNODB_FT_DEFAULT_STOPWORD", null);
	}

	/**
	 * Create an aliased <code>information_schema.INNODB_FT_DEFAULT_STOPWORD</code> table reference
	 */
	public InnodbFtDefaultStopword(String alias) {
		this(alias, INNODB_FT_DEFAULT_STOPWORD);
	}

	private InnodbFtDefaultStopword(String alias, Table<InnodbFtDefaultStopwordRecord> aliased) {
		this(alias, aliased, null);
	}

	private InnodbFtDefaultStopword(String alias, Table<InnodbFtDefaultStopwordRecord> aliased, Field<?>[] parameters) {
		super(alias, InformationSchema.INFORMATION_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InnodbFtDefaultStopword as(String alias) {
		return new InnodbFtDefaultStopword(alias, this);
	}

	/**
	 * Rename this table
	 */
	public InnodbFtDefaultStopword rename(String name) {
		return new InnodbFtDefaultStopword(name, null);
	}
}
