/**
 * This class is generated by jOOQ
 */
package com.example.mysql.tables;


import com.example.mysql.Keys;
import com.example.mysql.Mysql;
import com.example.mysql.tables.records.TimeZoneNameRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * Time zone names
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TimeZoneName extends TableImpl<TimeZoneNameRecord> {

	private static final long serialVersionUID = -699334912;

	/**
	 * The reference instance of <code>mysql.time_zone_name</code>
	 */
	public static final TimeZoneName TIME_ZONE_NAME = new TimeZoneName();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TimeZoneNameRecord> getRecordType() {
		return TimeZoneNameRecord.class;
	}

	/**
	 * The column <code>mysql.time_zone_name.Name</code>.
	 */
	public final TableField<TimeZoneNameRecord, String> NAME = createField("Name", org.jooq.impl.SQLDataType.CHAR.length(64).nullable(false), this, "");

	/**
	 * The column <code>mysql.time_zone_name.Time_zone_id</code>.
	 */
	public final TableField<TimeZoneNameRecord, UInteger> TIME_ZONE_ID = createField("Time_zone_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * Create a <code>mysql.time_zone_name</code> table reference
	 */
	public TimeZoneName() {
		this("time_zone_name", null);
	}

	/**
	 * Create an aliased <code>mysql.time_zone_name</code> table reference
	 */
	public TimeZoneName(String alias) {
		this(alias, TIME_ZONE_NAME);
	}

	private TimeZoneName(String alias, Table<TimeZoneNameRecord> aliased) {
		this(alias, aliased, null);
	}

	private TimeZoneName(String alias, Table<TimeZoneNameRecord> aliased, Field<?>[] parameters) {
		super(alias, Mysql.MYSQL, aliased, parameters, "Time zone names");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TimeZoneNameRecord> getPrimaryKey() {
		return Keys.KEY_TIME_ZONE_NAME_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TimeZoneNameRecord>> getKeys() {
		return Arrays.<UniqueKey<TimeZoneNameRecord>>asList(Keys.KEY_TIME_ZONE_NAME_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TimeZoneName as(String alias) {
		return new TimeZoneName(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TimeZoneName rename(String name) {
		return new TimeZoneName(name, null);
	}
}
