/**
 * This class is generated by jOOQ
 */
package com.example.sys.tables;


import com.example.sys.Sys;
import com.example.sys.tables.records.PsCheckLostInstrumentationRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * VIEW
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PsCheckLostInstrumentation extends TableImpl<PsCheckLostInstrumentationRecord> {

	private static final long serialVersionUID = 408838541;

	/**
	 * The reference instance of <code>sys.ps_check_lost_instrumentation</code>
	 */
	public static final PsCheckLostInstrumentation PS_CHECK_LOST_INSTRUMENTATION = new PsCheckLostInstrumentation();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PsCheckLostInstrumentationRecord> getRecordType() {
		return PsCheckLostInstrumentationRecord.class;
	}

	/**
	 * The column <code>sys.ps_check_lost_instrumentation.variable_name</code>.
	 */
	public final TableField<PsCheckLostInstrumentationRecord, String> VARIABLE_NAME = createField("variable_name", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

	/**
	 * The column <code>sys.ps_check_lost_instrumentation.variable_value</code>.
	 */
	public final TableField<PsCheckLostInstrumentationRecord, String> VARIABLE_VALUE = createField("variable_value", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * Create a <code>sys.ps_check_lost_instrumentation</code> table reference
	 */
	public PsCheckLostInstrumentation() {
		this("ps_check_lost_instrumentation", null);
	}

	/**
	 * Create an aliased <code>sys.ps_check_lost_instrumentation</code> table reference
	 */
	public PsCheckLostInstrumentation(String alias) {
		this(alias, PS_CHECK_LOST_INSTRUMENTATION);
	}

	private PsCheckLostInstrumentation(String alias, Table<PsCheckLostInstrumentationRecord> aliased) {
		this(alias, aliased, null);
	}

	private PsCheckLostInstrumentation(String alias, Table<PsCheckLostInstrumentationRecord> aliased, Field<?>[] parameters) {
		super(alias, Sys.SYS, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PsCheckLostInstrumentation as(String alias) {
		return new PsCheckLostInstrumentation(alias, this);
	}

	/**
	 * Rename this table
	 */
	public PsCheckLostInstrumentation rename(String name) {
		return new PsCheckLostInstrumentation(name, null);
	}
}
