/**
 * This class is generated by jOOQ
 */
package com.example.sys.tables;


import com.example.sys.Sys;
import com.example.sys.tables.records.StatementsWithRuntimesIn_95thPercentileRecord;

import java.math.BigInteger;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * VIEW
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatementsWithRuntimesIn_95thPercentile extends TableImpl<StatementsWithRuntimesIn_95thPercentileRecord> {

	private static final long serialVersionUID = -1475503206;

	/**
	 * The reference instance of <code>sys.statements_with_runtimes_in_95th_percentile</code>
	 */
	public static final StatementsWithRuntimesIn_95thPercentile STATEMENTS_WITH_RUNTIMES_IN_95TH_PERCENTILE = new StatementsWithRuntimesIn_95thPercentile();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<StatementsWithRuntimesIn_95thPercentileRecord> getRecordType() {
		return StatementsWithRuntimesIn_95thPercentileRecord.class;
	}

	/**
	 * The column <code>sys.statements_with_runtimes_in_95th_percentile.query</code>.
	 */
	public final TableField<StatementsWithRuntimesIn_95thPercentileRecord, String> QUERY = createField("query", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>sys.statements_with_runtimes_in_95th_percentile.db</code>.
	 */
	public final TableField<StatementsWithRuntimesIn_95thPercentileRecord, String> DB = createField("db", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>sys.statements_with_runtimes_in_95th_percentile.full_scan</code>.
	 */
	public final TableField<StatementsWithRuntimesIn_95thPercentileRecord, String> FULL_SCAN = createField("full_scan", org.jooq.impl.SQLDataType.VARCHAR.length(1).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>sys.statements_with_runtimes_in_95th_percentile.exec_count</code>.
	 */
	public final TableField<StatementsWithRuntimesIn_95thPercentileRecord, ULong> EXEC_COUNT = createField("exec_count", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>sys.statements_with_runtimes_in_95th_percentile.err_count</code>.
	 */
	public final TableField<StatementsWithRuntimesIn_95thPercentileRecord, ULong> ERR_COUNT = createField("err_count", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>sys.statements_with_runtimes_in_95th_percentile.warn_count</code>.
	 */
	public final TableField<StatementsWithRuntimesIn_95thPercentileRecord, ULong> WARN_COUNT = createField("warn_count", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>sys.statements_with_runtimes_in_95th_percentile.total_latency</code>.
	 */
	public final TableField<StatementsWithRuntimesIn_95thPercentileRecord, String> TOTAL_LATENCY = createField("total_latency", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>sys.statements_with_runtimes_in_95th_percentile.max_latency</code>.
	 */
	public final TableField<StatementsWithRuntimesIn_95thPercentileRecord, String> MAX_LATENCY = createField("max_latency", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>sys.statements_with_runtimes_in_95th_percentile.avg_latency</code>.
	 */
	public final TableField<StatementsWithRuntimesIn_95thPercentileRecord, String> AVG_LATENCY = createField("avg_latency", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>sys.statements_with_runtimes_in_95th_percentile.rows_sent</code>.
	 */
	public final TableField<StatementsWithRuntimesIn_95thPercentileRecord, ULong> ROWS_SENT = createField("rows_sent", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>sys.statements_with_runtimes_in_95th_percentile.rows_sent_avg</code>.
	 */
	public final TableField<StatementsWithRuntimesIn_95thPercentileRecord, BigInteger> ROWS_SENT_AVG = createField("rows_sent_avg", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(21).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>sys.statements_with_runtimes_in_95th_percentile.rows_examined</code>.
	 */
	public final TableField<StatementsWithRuntimesIn_95thPercentileRecord, ULong> ROWS_EXAMINED = createField("rows_examined", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>sys.statements_with_runtimes_in_95th_percentile.rows_examined_avg</code>.
	 */
	public final TableField<StatementsWithRuntimesIn_95thPercentileRecord, BigInteger> ROWS_EXAMINED_AVG = createField("rows_examined_avg", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(21).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>sys.statements_with_runtimes_in_95th_percentile.first_seen</code>.
	 */
	public final TableField<StatementsWithRuntimesIn_95thPercentileRecord, Timestamp> FIRST_SEEN = createField("first_seen", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>sys.statements_with_runtimes_in_95th_percentile.last_seen</code>.
	 */
	public final TableField<StatementsWithRuntimesIn_95thPercentileRecord, Timestamp> LAST_SEEN = createField("last_seen", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>sys.statements_with_runtimes_in_95th_percentile.digest</code>.
	 */
	public final TableField<StatementsWithRuntimesIn_95thPercentileRecord, String> DIGEST = createField("digest", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * Create a <code>sys.statements_with_runtimes_in_95th_percentile</code> table reference
	 */
	public StatementsWithRuntimesIn_95thPercentile() {
		this("statements_with_runtimes_in_95th_percentile", null);
	}

	/**
	 * Create an aliased <code>sys.statements_with_runtimes_in_95th_percentile</code> table reference
	 */
	public StatementsWithRuntimesIn_95thPercentile(String alias) {
		this(alias, STATEMENTS_WITH_RUNTIMES_IN_95TH_PERCENTILE);
	}

	private StatementsWithRuntimesIn_95thPercentile(String alias, Table<StatementsWithRuntimesIn_95thPercentileRecord> aliased) {
		this(alias, aliased, null);
	}

	private StatementsWithRuntimesIn_95thPercentile(String alias, Table<StatementsWithRuntimesIn_95thPercentileRecord> aliased, Field<?>[] parameters) {
		super(alias, Sys.SYS, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StatementsWithRuntimesIn_95thPercentile as(String alias) {
		return new StatementsWithRuntimesIn_95thPercentile(alias, this);
	}

	/**
	 * Rename this table
	 */
	public StatementsWithRuntimesIn_95thPercentile rename(String name) {
		return new StatementsWithRuntimesIn_95thPercentile(name, null);
	}
}
