/**
 * This class is generated by jOOQ
 */
package com.example.sys.tables;


import com.example.sys.Sys;
import com.example.sys.tables.records.UserSummaryByStatementLatencyRecord;

import java.math.BigInteger;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * VIEW
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSummaryByStatementLatency extends TableImpl<UserSummaryByStatementLatencyRecord> {

	private static final long serialVersionUID = 81482731;

	/**
	 * The reference instance of <code>sys.user_summary_by_statement_latency</code>
	 */
	public static final UserSummaryByStatementLatency USER_SUMMARY_BY_STATEMENT_LATENCY = new UserSummaryByStatementLatency();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<UserSummaryByStatementLatencyRecord> getRecordType() {
		return UserSummaryByStatementLatencyRecord.class;
	}

	/**
	 * The column <code>sys.user_summary_by_statement_latency.user</code>.
	 */
	public final TableField<UserSummaryByStatementLatencyRecord, String> USER = createField("user", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>sys.user_summary_by_statement_latency.total</code>.
	 */
	public final TableField<UserSummaryByStatementLatencyRecord, BigInteger> TOTAL = createField("total", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(42), this, "");

	/**
	 * The column <code>sys.user_summary_by_statement_latency.total_latency</code>.
	 */
	public final TableField<UserSummaryByStatementLatencyRecord, String> TOTAL_LATENCY = createField("total_latency", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>sys.user_summary_by_statement_latency.max_latency</code>.
	 */
	public final TableField<UserSummaryByStatementLatencyRecord, String> MAX_LATENCY = createField("max_latency", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>sys.user_summary_by_statement_latency.lock_latency</code>.
	 */
	public final TableField<UserSummaryByStatementLatencyRecord, String> LOCK_LATENCY = createField("lock_latency", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>sys.user_summary_by_statement_latency.rows_sent</code>.
	 */
	public final TableField<UserSummaryByStatementLatencyRecord, BigInteger> ROWS_SENT = createField("rows_sent", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(42), this, "");

	/**
	 * The column <code>sys.user_summary_by_statement_latency.rows_examined</code>.
	 */
	public final TableField<UserSummaryByStatementLatencyRecord, BigInteger> ROWS_EXAMINED = createField("rows_examined", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(42), this, "");

	/**
	 * The column <code>sys.user_summary_by_statement_latency.rows_affected</code>.
	 */
	public final TableField<UserSummaryByStatementLatencyRecord, BigInteger> ROWS_AFFECTED = createField("rows_affected", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(42), this, "");

	/**
	 * The column <code>sys.user_summary_by_statement_latency.full_scans</code>.
	 */
	public final TableField<UserSummaryByStatementLatencyRecord, BigInteger> FULL_SCANS = createField("full_scans", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(43), this, "");

	/**
	 * Create a <code>sys.user_summary_by_statement_latency</code> table reference
	 */
	public UserSummaryByStatementLatency() {
		this("user_summary_by_statement_latency", null);
	}

	/**
	 * Create an aliased <code>sys.user_summary_by_statement_latency</code> table reference
	 */
	public UserSummaryByStatementLatency(String alias) {
		this(alias, USER_SUMMARY_BY_STATEMENT_LATENCY);
	}

	private UserSummaryByStatementLatency(String alias, Table<UserSummaryByStatementLatencyRecord> aliased) {
		this(alias, aliased, null);
	}

	private UserSummaryByStatementLatency(String alias, Table<UserSummaryByStatementLatencyRecord> aliased, Field<?>[] parameters) {
		super(alias, Sys.SYS, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserSummaryByStatementLatency as(String alias) {
		return new UserSummaryByStatementLatency(alias, this);
	}

	/**
	 * Rename this table
	 */
	public UserSummaryByStatementLatency rename(String name) {
		return new UserSummaryByStatementLatency(name, null);
	}
}
