/**
 * This class is generated by jOOQ
 */
package com.example.sys.tables;


import com.example.sys.Sys;
import com.example.sys.tables.records.X$userSummaryByFileIoRecord;

import java.math.BigInteger;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * VIEW
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class X$userSummaryByFileIo extends TableImpl<X$userSummaryByFileIoRecord> {

	private static final long serialVersionUID = 1047940132;

	/**
	 * The reference instance of <code>sys.x$user_summary_by_file_io</code>
	 */
	public static final X$userSummaryByFileIo X$USER_SUMMARY_BY_FILE_IO = new X$userSummaryByFileIo();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<X$userSummaryByFileIoRecord> getRecordType() {
		return X$userSummaryByFileIoRecord.class;
	}

	/**
	 * The column <code>sys.x$user_summary_by_file_io.user</code>.
	 */
	public final TableField<X$userSummaryByFileIoRecord, String> USER = createField("user", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>sys.x$user_summary_by_file_io.ios</code>.
	 */
	public final TableField<X$userSummaryByFileIoRecord, BigInteger> IOS = createField("ios", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(42), this, "");

	/**
	 * The column <code>sys.x$user_summary_by_file_io.io_latency</code>.
	 */
	public final TableField<X$userSummaryByFileIoRecord, BigInteger> IO_LATENCY = createField("io_latency", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(42), this, "");

	/**
	 * Create a <code>sys.x$user_summary_by_file_io</code> table reference
	 */
	public X$userSummaryByFileIo() {
		this("x$user_summary_by_file_io", null);
	}

	/**
	 * Create an aliased <code>sys.x$user_summary_by_file_io</code> table reference
	 */
	public X$userSummaryByFileIo(String alias) {
		this(alias, X$USER_SUMMARY_BY_FILE_IO);
	}

	private X$userSummaryByFileIo(String alias, Table<X$userSummaryByFileIoRecord> aliased) {
		this(alias, aliased, null);
	}

	private X$userSummaryByFileIo(String alias, Table<X$userSummaryByFileIoRecord> aliased, Field<?>[] parameters) {
		super(alias, Sys.SYS, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public X$userSummaryByFileIo as(String alias) {
		return new X$userSummaryByFileIo(alias, this);
	}

	/**
	 * Rename this table
	 */
	public X$userSummaryByFileIo rename(String name) {
		return new X$userSummaryByFileIo(name, null);
	}
}
